version: 1

sources:
  - name: public
    description: Набор данных для хранения сырых данных
    tables:
      - name: artists
        description: Таблица с сырыми данными из api yandex_music по методу сlient.artists_brief_info
      - name: albums
        description: Таблица с сырыми данными из api yandex_music по методу client.artists_direct_albums
      - name: tracks
        description: Таблица с сырыми данными из api yandex_music по методу client.artists_tracks
      - name: popular_tracks
        description: Таблица с сырыми данными из api yandex_music по методу сlient.artists_brief_info
      - name: similar_artists
        description: Таблица с сырыми данными из api yandex_music по методу сlient.artists_brief_info
      - name: artists_metrics
        description: Таблица с метриками (likes_count, ratings_month, ratings_week, ratings_day), создана на основе таблицы artists
      - name: albums_metrics
        description: Таблица с метрикой (likes_count), создана на основе таблицы albums
