name: dbt_docs_updating

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python and DBT
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres # Установите нужные адаптеры

      - name: Generate DBT Docs
        run: |
          dbt docs generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./target
